# Generated by Django 4.2 on 2024-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "TMPID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("TMPName", models.CharField(blank=True, max_length=20, null=True)),
                ("steamID", models.PositiveBigIntegerField(blank=True, null=True)),
                ("QQ", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
