# Generated by Django 4.2 on 2024-06-02 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Users", "0002_userinfo_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
