# Generated by Django 4.2 on 2024-06-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0004_alter_userinfo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="credit",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
